# Generated by Django 5.2.3 on 2025-06-30 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activeusers',
            fields=[
                ('Raduser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.radacct')),
                ('Radip', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
