radiusserver1	"127.0.0.1"
radiusserver2	"127.0.0.1"
radiussecret	"testing123"
radiusauthport  1812
radiusacctport  1813
uamserver	"http://10.0.0.1/accounts/login/"
radiusnasid	"nas01"
papalwaysok
uamaliasname "chilli"
adminupdatefile "/etc/chilli/local.conf"

